language: node_js
sudo: false
node_js:
  - 5
cache:
  directories:
    - node_modules
env:
  global:
    - 'NPM_CONFIG_PROGRESS="false"'
    # GITHUB_TOKEN
    - secure: al5RwlhI0nDmDs+06igH+KTzaQQt/xvp996UHMDOXU3sMvpUysxqKS3VlMGoNPGTmp87c1Egz8LFB7V4dM14BhIbZbNKNpDV6MG7e0TqZ/IZUZ+4rq7n096hKZWLkQVQlFECmIi6JI82Fs3AZ/ht+PdMroKNcsf91K9SrEw1N2kL/2KSeB7ncoXyR/IOiikj20ZiqWkHM+FW8hh9sMqmi5KmRZ5LIB2UZhbUYDhiC5cVenkZpcOOdslnOTL3uwZYDAz1pLSxX0GtPvFDh3RSqv+9fGLdrouX4gzKfHsqhRf7K2y6/wxVCJwk/eh/wJ6B8x22LUEMwuIpXNftE3s/cnKPAmeuMHwek40B7OacCBj6f1ZED/6ns+6lQE8tzS5zb+wL9UWWMeor4JE0EGOYLHvdewZBwP42ypXnUrkxRNI6eoOfDSrOZmvsRWZBRFTc/Oa1bYeYlMz8+sYdh4uDiS/acyhA5NahOlpSSztOUCUE7O22H0icVp2XY3Z9ZlO5ykBymyGLRcqvp8jbu6eJftt6ezzR0KJ4kk2D+HesoX0K2IB2Q2vFM+n3we3XrV5yEP/1Z4/4w5zzuFKOOL0AbFbjv9Kj0vU2GsvN2B44F9PzfBeKUnY5tQ8HtrAkjXt4jdnQdU9zNVncqYVnh01n8/oNIJKDHvNa5uzU0R7Uquw=
before_install:
  - npm prune
before_deploy:
  - 'git config --global user.email "gh-pages@localhost"'
  - 'git config --global user.name "npm gh-pages"'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  'on':
    branch: master
    node: '5'
