backend:
  name: github
  repo: armada-ths/armada.nu
  branch: master

public_folder: "/assets"
media_folder: "content/assets"
publish_mode: editorial_workflow


collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    sort: "date:desc" # Default is title:asc
    slug: "{{slug}}"
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "News"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover_wide", name: "cover_wide", widget: "image", required: false}
      - {label: "Cover_square", name: "cover_square", widget: "image", required: false}
      - {label: "Ingress", name: "ingress", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "string", default: "Page"}
      - {label: "Header", name: "header", widget: "image", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
 
